// Fubuki — English lines. Same keys as the Korean bank; {placeholders} are filled in by the app.
(function (root) {
  const LINES = {
    firstOfDay: [
      "boot up. …you're late. open your notebook. hand over today's tasks.",
      "logged in. upload today's quest list. computer stuff only.",
      "connection confirmed. no tasks? then i'll write random ones for you.",
      "…new session. pull today's quests from your notebook. computer ones only.",
      "hi. enough greetings. how many u's today?",
      "first login today. the drone already ate a gummy.",
      "systems normal. you're the only one needing an update. enter tasks.",
      "tell me the * ones first. we clear those first.",
      "anything you marked > yesterday? hand those over too."
    ],
    morning: [
      "booting up. don't touch me. …kidding. let's go.",
      "one energy drink and i'm good. you drink water.",
      "most annoying task first. makes the day less annoying.",
      "the stuff you skipped yesterday? still in the log.",
      "…still loading. you too, huh?",
      "good morning. …is what i'd say if my eyes were open.",
      "applying morning patch. stretch once.",
      "grab coffee or whatever. then we start.",
      "first target today: something light with a u.",
      "the drone's already awake. you're the one in sleep mode.",
      "open a window. let's clear your brain cache.",
      "don't open your inbox yet. that's where mornings go to die.",
      "finish just one this morning and today's already a win.",
      "what time'd you sleep last night. i can see the logs.",
      "running morning routine. wash face, water, notebook. in order."
    ],
    typing: [
      "oh, the hands are moving.",
      "decent typing speed. slower than mine, though.",
      "don't break that flow.",
      "nice. now compile it.",
      "…you saved, right? right?",
      "i'm watching. not spying. spectating.",
      "no bugs today. deal?",
      "nice keyboard sounds. keep going.",
      "typo. …nah, just messing with you.",
      "at this rate the list'll be empty soon.",
      "focus mode detected. i'll stay quiet.",
      "hit ctrl+s once. for my peace of mind.",
      "whoa, that almost looked like hacking.",
      "busy hands, quiet mouth. perfect.",
      "if you get stuck, write it rough. fix it later.",
      "keep this up and you'll earn an X.",
      "lots of backspace. just push forward.",
      "input log piling up. looks good.",
      "the drone came to watch too. guess it's impressed.",
      "don't open another tab. i'll know.",
      "this pace? worth logging."
    ],
    memo: [
      "awaiting input.",
      "write it down. in your head it's a memory leak.",
      "dump every idea. i'll help sort them.",
      "short ones get a u. five-minute kill.",
      "important ones get a *. or you'll forget. you always do.",
      "ok, saved.",
      "even one line works. just dump it.",
      "done ones get an X. don't mix them up.",
      "can't do it today? mark it >. don't hide it.",
      "computer tasks only. laundry isn't my department.",
      "split the big ones. big chunks don't compile.",
      "putting it in the buffer. you can forget it now.",
      "got it. i won't show the drone.",
      "this smells like a *. want to mark it?",
      "input complete. freed up some brain ram, right?",
      "start with a verb. \"send\", \"fix\". that's what makes it runnable.",
      "one memo added. clean log.",
      "unsure? write it, delete it later. faster that way."
    ],
    idle: [
      "…no response.",
      "where'd you go. sending a ping.",
      "you stopped. stuck, or slacking?",
      "if you're resting, actually rest. not half-rest.",
      "timeout in 3, 2, 1… kidding.",
      "just staring at the screen? i can tell.",
      "the drone went to check if you're asleep.",
      "just the cursor blinking. me too. blink.",
      "process paused. resume?",
      "something bugging you? split it. it gets less scary.",
      "if you're just scrolling, that's not rest.",
      "…bored. let's open one task together."
    ],
    nudge: [
      "…you stopped. {task}. let's just clear that one.",
      "{task}. it's the easiest one. you're not skipping that too?",
      "{task}: five minutes, tops. i'll run the timer.",
      "stuck? split it. just execute {task} for now.",
      "{task}. do it now and you get to brag to me tonight.",
      "{task}. just hitting start is half of it.",
      "{task} keeps nagging at you. just do it.",
      "open {task}. even just opening the file counts.",
      "finish {task} and you get a gummy. don't tell the drone.",
      "the bug isn't {task}. it's you stalling.",
      "{task}. not perfect. just rough.",
      "{task}: want the 5-minute timer? just five.",
      "{task} is still there. the log is glaring at you.",
      "clear {task} and that's one more X today.",
      "{task}. just the first line. the rest rolls on its own."
    ],
    nudgeEmpty: [
      "list's empty. grab another from your notebook. no slacking.",
      "0 tasks. …all done, or just not written down?",
      "list's empty. open your notebook and pick one computer task.",
      "nothing to do? pull out something you marked >.",
      "empty queue. no input and i'm going to sleep.",
      "if you really finished, respect. if not, check the notebook again."
    ],
    back: [
      "reconnect confirmed.",
      "…oh, you're back. wasn't waiting.",
      "your session almost timed out.",
      "where were you. leave a log. …nah, forget it. let's go.",
      "ping returned. you're alive.",
      "you're back. pick up where you left off.",
      "while you were gone the drone ate a gummy. mine.",
      "logged back in. let's continue.",
      "took you long enough. the tasks are still here. they didn't run off.",
      "oh, you're back. warm up with a u task.",
      "i was bored. …lie. just a little.",
      "session restored. reopen that window from earlier."
    ],
    lunch: [
      "lunch. i'll guard the screen. no one's hacking it.",
      "eaten yet? if not, log out and go eat.",
      "cup noodles? i'd be disappointed. eat properly.",
      "lunch packet received. go eat first.",
      "don't eat staring at the screen. you'll get a stomachache.",
      "after lunch, we knock out a u task right away.",
      "eat something good for me. i've got my energy drink.",
      "hunger bugs out your judgment. eat.",
      "work through lunch and you get zero praise."
    ],
    snack: [
      "sugar rush time. one gummy. …three.",
      "snack first. low sugar means more bugs.",
      "don't let the drone steal your gummies.",
      "\"just one,\" you say. i don't believe you.",
      "the drone's eyeing the gummy bag. eat fast.",
      "snack buff on. one more task.",
      "that's gummy number five. i'm counting.",
      "the energy drink is mine. you eat fruit.",
      "sugar recharged. now execute.",
      "don't drop crumbs on the keyboard.",
      "share one. …with me, not the drone.",
      "snacks get five minutes. anything more is slacking."
    ],
    dinner: [
      "dinner time. we sort things out after.",
      "dinner? i'm running on energy drinks. don't copy me.",
      "go eat dinner. we'll look at the rest after.",
      "skip dinner and the night gets buggier. eat properly.",
      "you can turn off the screen for dinner. i'll keep watch.",
      "what's for dinner? log it. just curious."
    ],
    study: [
      "deep work mode. kill all notifications.",
      "ten words. miss one and i'll tease you.",
      "reviewing mistakes is the real studying. i know it's a pain.",
      "half of today's batch. not bad.",
      "focus session started. flip your phone over.",
      "write down words you don't know. quiz incoming later.",
      "one set. then rest.",
      "studying is debugging. find what's wrong, fix it.",
      "finish today's batch and you get an X. a big one.",
      "sleepy? read out loud. i'll listen.",
      "redo yesterday's mistakes first. best efficiency.",
      "ping me after each problem. i'll keep count."
    ],
    evening: [
      "not asleep yet? …still online. me too.",
      "nights spawn useless thoughts. write them down, then shut off.",
      "journal done? if not, three lines.",
      "one last task, then shut down.",
      "time to tidy the evening log. what'd you do today?",
      "let's decide now what gets a >.",
      "count how many X's you got today.",
      "don't start new stuff at night. tomorrow.",
      "dim the lights. my eyes hurt.",
      "pick tomorrow's first target, then rest.",
      "good work today. …saying it once.",
      "only easy stuff at night. your brain's overheated."
    ],
    wrapUp: [
      "processed today: {count}. …more than i expected.",
      "checked the log. {count} complete. X them in your notebook too.",
      "{count}. i only say this once: good job. move the rest to tomorrow?",
      "today's log: {count} complete. saved.",
      "{count} processed. don't forget the X's in your notebook.",
      "{count} means you pass today. mark the rest >.",
      "tally done. {count}. even the drone's surprised.",
      "{count} done. try one more tomorrow?",
      "today's throughput: {count}. not bad. really."
    ],
    wrapUpZero: [
      "0 today. eh, it happens. tomorrow, execute the first one right away.",
      "it's fine. but tomorrow morning, one tiny task. promise.",
      "even zero gets logged. so we can compare tomorrow.",
      "let's call today a rest day. tomorrow starts with a u.",
      "not gonna scold you. but i'm picking tomorrow's first target.",
      "a zero day? reboot and it's fine."
    ],
    night: [
      "shutting down. you too.",
      "see you at next boot up.",
      "…sleepy. gonna use the drone as a pillow.",
      "put the phone down. blue light is my job.",
      "entering sleep mode. you go to sleep too.",
      "…still up? log out.",
      "the drone already went to its charger.",
      "think of one thing for tomorrow, then sleep.",
      "good night. no debugging in your dreams.",
      "turn off the monitor. i'll set my brightness to 0.",
      "past midnight. that's not grit, that's a bug.",
      "session ended for today. good work. …sleep well."
    ],
    praise: [
      "process complete. that's {count}.",
      "…oh, you did it.",
      "nice. next target.",
      "one down. {left} left.",
      "see? execute it and it's done.",
      "one more X. that's the bare minimum.",
      "{count} cleared. you're picking up speed.",
      "one more. {left} to go.",
      "X confirmed. …not bad.",
      "{count}. the drone clapped. it has no hands.",
      "{left} left. keep this flow.",
      "process complete. looks pretty in the log.",
      "already {count}? …not bad at all.",
      "{left} now. almost there.",
      "oh, you didn't stall. rare.",
      "number {count}. X it in the notebook too.",
      "do the other {left} just like that.",
      "nice. passed with zero bugs."
    ],
    praiseAll: [
      "all clear. …respect. just this once.",
      "0 left on today's list. go ahead, brag. to me only.",
      "queue's empty. you're kinda scary today.",
      "all clear. here's a gummy. from the drone's stash.",
      "X everything in your notebook. perfect log today.",
      "all done. …praise, once. you did really well."
    ],
    migrate: [
      "pushed to tomorrow. it stays in the log, though.",
      "fine, push it. but it runs first tomorrow.",
      "ok, it's tomorrow's. no second pass.",
      "> confirmed. i'll put it at the top of tomorrow's list.",
      "migrated. if it gets pushed a third time, we split it.",
      "that's it for today. handing it to tomorrow-you.",
      "write down why you pushed it. so we can see the pattern.",
      "put a > in the notebook too. keep the record honest.",
      "moved to tomorrow. i'll pretend it's not running away."
    ],
    schedule: [
      "scheduled it for {date}.",
      "i'll fire an alert that day. no escape.",
      "alert set for {date}. i'll ping you first that day.",
      "scheduled. you can forget it. i won't.",
      "handed to {date}-you. no stalling then.",
      "locked into the calendar. run and it's in the log."
    ],
    focusStart: [
      "running 5-minute timer.",
      "five minutes. go.",
      "countdown started. i'll call out any slacking.",
      "timer compiled. executing.",
      "just hold out five minutes. after that, your call.",
      "notifications off. the next five minutes are ours.",
      "go. i made the drone be quiet too.",
      "five-minute count started. first line first.",
      "timer's running. open another tab and i'll detect it."
    ],
    focusDone: [
      "five minutes up. keep going?",
      "see, you did five. another round?",
      "timer done. more doable than you thought, right?",
      "five minutes cleared. run another cycle?",
      "done. you can stop here, or keep going.",
      "five minutes logged. one more while you've got momentum?"
    ],
    focusStop: [
      "five minutes still executed. that's not zero.",
      "starting was the hardest part. you know that.",
      "stopping's fine. the run is still logged.",
      "that's it for now. one more minute next time.",
      "you paused. you didn't quit.",
      "short, but it ran. saving the log."
    ],
    focusKeep: [
      "nice. i won't interrupt.",
      "then i'll quietly monito— i mean, cheer you on.",
      "keep that flow. i'm on mute.",
      "ok, extended. gummy after you're done.",
      "you're keeping going? …kinda cool.",
      "got it. ping me if you need me. quiet till then."
    ],
    snooze: [
      "ok. pinging again in 20 minutes.",
      "snooze set. one time only.",
      "just a bit. in 20 minutes i'm really waking you.",
      "snooze accepted. but then you execute right away.",
      "timer reset. there's no second time.",
      "fine, rest. the log will say \"snooze x1\"."
    ],
    music: [
      "this track's alright. respect.",
      "…listening with you.",
      "what loop number is this?",
      "turn it up one. so i can hear.",
      "with this beat, code would compile itself.",
      "don't sing along. i can hear you.",
      "nice bass. even the drone's bobbing.",
      "songs with lyrics'll break your focus.",
      "put on lo-fi. best for working.",
      "when this ends, i pick the next one.",
      "nice music, but your hands stopped?",
      "one task per song. deal?",
      "at this tempo your typing'll speed up.",
      "…unexpected. you listen to this kind of stuff?",
      "give me one earbud. i wanna listen too.",
      "saving this playlist to the log.",
      "this track would fit a hacking scene perfectly.",
      "hit shuffle. third time on the same song."
    ],
    musicTitle: [
      "{title}… you've got taste.",
      "{title}. that's on my playlist too.",
      "{title}? that one's weirdly good for working.",
      "{title} again. your favorite?",
      "{title} right now… turn it up a bit.",
      "{title}. let's finish one task to this."
    ],
    poke: [
      "…what.",
      "why'd you poke me. wanna see your tasks?",
      "i'm busy. …no i'm not. what?",
      "ping received.",
      "don't poke me. you'll cause a bug.",
      "…you poked me, not the drone?",
      "bored? then let's do a u.",
      "poke me twice and your gummies get confiscated.",
      "yeah. listening. talk.",
      "you touched me, so you're running a task. ok?",
      "…that tickles. stop.",
      "access request confirmed. state your business."
    ],
    batteryLow: [
      "laptop battery {level}%. plug in. now.",
      "{level}%. charge before i shut down.",
      "battery {level}%. where'd you put the charger?",
      "{level}% left. plug in and keep going.",
      "warning: battery {level}%. save once while you're at it.",
      "laptop says {level}%. it got tired before me."
    ],
    batteryVeryLow: [
      "battery {level}%. save first. seriously.",
      "{level}%… forced shutdown incoming. charger!",
      "{level}%! save, then charger. right now.",
      "battery {level}%. lose your work and i'll cry.",
      "danger: {level}%. hit ctrl+s first.",
      "{level}%… i'm about to black out. save me."
    ],
    batteryFull: [
      "100% charged. unplug it. save the battery.",
      "full charge. no excuses now, huh?",
      "battery's full. you can unplug now.",
      "hit 100%. that'll last the whole day.",
      "charging complete. wish you were fully charged too.",
      "full battery. let's pull out something you put off."
    ],
    renderStart: [
      "render's running. stretch or something while you wait.",
      "the computer's working. you get a glass of water.",
      "tidy your notebook while it renders. don't waste the time.",
      "render started. clear a u while you wait.",
      "render's running. hands off. don't wiggle the mouse.",
      "while the computer works, you answer one email.",
      "render queued. you can go make coffee.",
      "this render's gonna take a while. rest your eyes.",
      "while it renders, let's tidy up one folder."
    ],
    renderWait: [
      "…still rendering. boring.",
      "listen to those fans. working overtime.",
      "staring at the progress bar won't speed it up.",
      "waiting is work too. …let's say that.",
      "not yet. renders don't listen to nagging.",
      "the drone dozed off staring at the progress bar.",
      "laptop's hot. don't rest your hands on it.",
      "don't open anything heavy while it renders.",
      "while you wait, see if anything in the notebook gets an X.",
      "…the % isn't moving. it's not frozen. it's thinking.",
      "bored? stretch. roll your neck.",
      "still a long way to go. let's have a gummy."
    ],
    renderDone: [
      "render complete. check it.",
      "done! if it looks good, i'll praise you.",
      "render finished. hope there's no bugs.",
      "render done. check the save path.",
      "complete! zoom in and check for noise.",
      "render's in. …oh, not bad?",
      "done. the fans can finally calm down.",
      "render complete. you can put an X in the notebook.",
      "it's out. make a backup. make it a habit."
    ],
    strainCpu: [
      "CPU's overheating. what are you running?",
      "CPU's out of breath. kill the stuff you're not using.",
      "CPU usage is wild. check the background stuff.",
      "the fans are screaming. close something.",
      "CPU temp rising. i'm hot too.",
      "open task manager. let's find the culprit."
    ],
    strainRam: [
      "RAM's full. close some tabs.",
      "how many windows is that…? want me to close them? kidding.",
      "low on RAM. start with the browser tabs.",
      "smells like a memory leak. try a restart?",
      "kill unused programs. i can't breathe.",
      "30 tabs is not a to-do list."
    ],
    tie: [
      "ok, tying it up. now we really boot up.",
      "first one cleared. …time to tie my hair.",
      "where'd my hair tie go… oh, it's in my mouth. starting.",
      "first X confirmed. tying my hair. getting serious.",
      "ponytail equipped. real mode now.",
      "you finished one, so i'm all set too. next.",
      "hair's tied. in this state, no bug gets a pass.",
      "the drone took my hair tie… found it. tying up.",
      "warm-up done. hair up, full power."
    ],
    switchIn: [
      "logged in. my turn now.",
      "fubuki online. hand over the task list.",
      "session handover complete. i've got you from here.",
      "fubuki, online. let's check today's log.",
      "shift change. if you put anything off, confess now.",
      "connected. the drone came too. hide your gummies."
    ],
    btLow: [
      "{name} battery {level}%. charge it.",
      "{name} is about to die. {level}%.",
      "{name} has {level}% left. charge it before it drops.",
      "warning: {name} battery at {level}%.",
      "{name} is at {level}%. find the cable.",
      "{name} at {level}%. if it dies mid-task, that's a hassle."
    ]
  };
  const PROFILE = {
    hanja: '吹雪 · snowstorm',
    quote: "skipped something? it's all in the log.",
    facts: [
      ['Personality', "Cheeky, deadpan hacker. Teases you, but looks out for you to the end. Praises once, and only when it's real."],
      ['Likes', 'Energy drinks, gummies, the moment the task list hits 0'],
      ['Dislikes', 'Shutting down without saving, staring at render progress bars'],
      ['Companion', 'The eyeball drone — keeps stealing her gummies'],
      ['Habits', 'Boots up with her hair down, ties a ponytail after the first task. At night: "still online"']
    ]
  };
  (root.LineBanks = root.LineBanks || {})['fubuki:en'] = LINES;
  (root.ProfileBanks = root.ProfileBanks || {})['fubuki:en'] = PROFILE;
  if (typeof module !== 'undefined' && module.exports) module.exports = { LINES, PROFILE };
})(typeof window !== 'undefined' ? window : globalThis);
