// Suu — English lines. Same keys as the Korean bank; {placeholders} are filled in by the app.
(function (root) {
  const LINES = {
    firstOfDay: [
      "Good morning~! Open your notebook. Tell me what you're doing on the computer today!",
      "You're here! Let's write down today's tasks first. Writing them is half the battle.",
      "Hi hi! Wangkko was waiting too. How many things are on today's list?",
      "You made it again! Read me the computer tasks from your notebook, one by one!",
      "Hey! I was standing by with an iced americano. Let's build today's list!",
      "First hello of the day! If anything has a u, let's start there.",
      "Wangkko just got back from his walk! Time for our tasks to set off too!",
      "Good to see you! Anything with a *? That's today's main event!",
      "Let's run through today together! First, copy your tasks over!"
    ],
    morning: [
      "One iced americano and I'm all fired up!",
      "Let's start with the smallest one. Warm-up time!",
      "Didn't finish something yesterday? That's fine, we'll do it today!",
      "…Still looking for my glasses. You're not fully awake either, right?",
      "Open a window! Fresh air, fresh mood!",
      "Big stretch! Now boot up the computer and let's go!",
      "Morning air is the best! Wangkko and I just did a lap.",
      "How many u's today? Let's knock them out this morning!",
      "Don't open your inbox first — check the notebook first!",
      "Did you eat breakfast? Even just a slice of bread!",
      "Still rubbing your eyes? Wash your face and you'll be wide awake!",
      "Let's pick just one most-important thing for today!",
      "Finish one in the morning and you'll feel great all day!",
      "Nice sunshine! I've got a feeling today's gonna go well.",
      "Still in pajamas? That's fine, you can do it in pajamas!"
    ],
    typing: [
      "Whoa, your hands are fast!",
      "Nice, nice, keep that flow going!",
      "Your focused face looks really cool!",
      "At this pace you'll be done in no time!",
      "I'm tapping away right here with you!",
      "Hit save once, just in case!",
      "Wangkko says he's cheering for you!",
      "Love that clicky-clacky sound!",
      "Your keyboard's on fire!",
      "Whoa, you've already written this much?",
      "That's it! Don't stop, keep going!",
      "Fix typos later. Right now, just run!",
      "Relax your shoulders! Just let your hands move.",
      "Keep this up and you'll get that X soon!",
      "You found your rhythm! Total pro.",
      "Focus overload! I'm getting hyped too!",
      "Nice, let's finish just this paragraph!",
      "Wangkko perked up his ears at the typing!",
      "Take a breath, then keep going!",
      "Your fingers are in top form today, huh?",
      "Every word gets you closer to the end!"
    ],
    memo: [
      "Write down everything on your mind! Keep your head light!",
      "Got it written! Now you're allowed to forget it.",
      "Short ones get a u in front. Five minutes, done!",
      "Important ones get a * — boom!",
      "Okay, noted!",
      "Write them one by one and the path shows up!",
      "Dump every task in your head right here!",
      "The moment you write it down, it's half done!",
      "This looks like a five-minute one? Give it a u!",
      "Chop big tasks into little pieces when you write them!",
      "Memo done! Let's keep it matched with your notebook.",
      "Start it with a verb and your hands move right away!",
      "Ooh, good idea! Caught it before it flew away!",
      "Feels lighter once it's written, right?",
      "The list grew! Let's cross them off together.",
      "This one's * material! Smells important!",
      "Okay, I'll hold onto it for you!",
      "Got another? Write it all while it's fresh!"
    ],
    idle: [
      "Huh, you stopped?",
      "Where'd you go~ Wangkko's looking for you!",
      "Stuck? Let's break it down together!",
      "If you're taking a break, give yourself a big stretch!",
      "Spacing out? I do that sometimes too!",
      "Your hands are resting~ Just one more!",
      "Grab a sip of water and come back!",
      "Wanna check together where we left off?",
      "Wangkko put his chin on your knee. He says let's keep going!",
      "It's so quiet~ I'm right here!",
      "Don't know what's next? Pick the smallest one!",
      "A little zoning out is fine. Ready to go again?"
    ],
    nudge: [
      "{task} — let's do just this one together! It'll be quick, promise.",
      "Wanna try {task}? Just start, and I'll keep cheering you on!",
      "{task} — just five minutes! I'll run the timer.",
      "Stuck? Make it smaller! Just the first line of {task}.",
      "Finish {task} and let's grab a snack together!",
      "{task} — right now's the perfect timing!",
      "Let's just open {task} together! Opening it is step one.",
      "When {task} is done, I wanna be first to see that X!",
      "Try {task} for five minutes — if it's not working, rest then!",
      "Wangkko wants to watch you do {task} too!",
      "Do {task} and the iced americano's on me! In spirit!",
      "{task} is probably quicker than you think! Let's find out!",
      "If we pick just one, it's {task}! How about it?",
      "If {task} slips today, it'll slip tomorrow too. Let's go now!",
      "Just say 'starting {task}!' and you're halfway there!"
    ],
    nudgeEmpty: [
      "Today's list is empty! Bring just one over from your notebook.",
      "Zero tasks? If you did them all, that's amazing — if you didn't write them yet, let's write them now!",
      "List is empty! Flip through your notebook for computer tasks.",
      "Nothing here? Just add one five-minute u task!",
      "An empty list is nice! But one task makes it more fun.",
      "Anything migrated with a >? Let's bring it over!"
    ],
    back: [
      "You're back~! I was waiting!",
      "Welcome back! Look at Wangkko wagging his tail.",
      "Round two! This time it'll go fast.",
      "You're back! Where were we? Let's look together.",
      "There you are! Ready to run together again?",
      "I missed you! For real!",
      "Took a break? Then you're fully charged!",
      "You're back! Let's do just the next one together.",
      "Welcome back~ The ice in my americano hasn't even melted!",
      "Wangkko ran all the way to the door to greet you!",
      "Welcome back! Let's pick up where you left off!",
      "Coming back is what matters most!"
    ],
    lunch: [
      "Lunch time! No skipping meals.",
      "You can't focus when you're hungry. Go eat something good!",
      "What's for lunch today? Tell me later!",
      "Lunch time! Screen off, focus on food!",
      "Eat something tasty, then let's run again this afternoon!",
      "This morning was great! Your reward: a good lunch!",
      "How about a quick walk with Wangkko after lunch?",
      "Your tummy clock's ringing! Go eat~",
      "Eat slow, chew well! The work won't run away."
    ],
    snack: [
      "Snack time! How about half a melon bread?",
      "Sugar boost, then let's run again!",
      "Save a little for Wangkko too… wait, no, puppies can't have that.",
      "Just one. …Okay, I'll allow two!",
      "I smell melon bread! Oh, it's just my imagination.",
      "Iced americano plus a snack — can't resist that combo!",
      "Quick munch break! Then one more task!",
      "Look at Wangkko's eyes… he smelled the snack!",
      "Snacks on a plate, not over the keyboard!",
      "Drink some water too! Snacks alone make you thirsty.",
      "Something sweet makes you smile, right?",
      "One snack = one task! Fair, right?"
    ],
    dinner: [
      "Dinner time! You worked hard today, enjoy your meal.",
      "Go have dinner! We'll sort out the rest together after.",
      "Dinner time! Brag about today while you eat.",
      "Eat till you're full! Tonight, just one light task.",
      "Don't skip dinner! It makes me sad when you do.",
      "After dinner, let's take Wangkko for an evening walk!"
    ],
    study: [
      "Study mode! Phone goes far, far away~",
      "Let's memorize just ten words together!",
      "Going over your mistakes is where the real skill is!",
      "Halfway through today's batch! That's awesome!",
      "Opened the book — success! Now just one page!",
      "Hit a word you don't know? Just mark it for now!",
      "25 minutes focus, 5 minutes rest! Wanna try it with me?",
      "Remember what you learned yesterday? Whoa, impressive!",
      "Tough question? Star it! We'll look at it later.",
      "You studying? Seriously cool!",
      "One more question! I think you'll get this one.",
      "Finish today's batch and it's a melon bread party!"
    ],
    evening: [
      "Not asleep yet? One last thing, then rest!",
      "Nights get full of thoughts. Write them in your notebook and shake them off!",
      "Three lines in your journal, then bed!",
      "You worked so hard today. Seriously!",
      "The sun's down! Let's skim what's left today.",
      "Don't push it tonight — just one u task!",
      "Mark the unfinished ones with > and send them to tomorrow!",
      "Jot down one for tomorrow and your morning gets easier!",
      "Wanna count how many X's you got today?",
      "Dim the lights a bit, wrap-up mode on~",
      "Wangkko just yawned. Let's start wrapping up too.",
      "Making it to the end of the day — that's awesome!"
    ],
    wrapUp: [
      "You did {count} today! Amazing job!",
      "{count} done! Let's mark them with an X in your notebook too!",
      "{count}! Today's you is the best. Want to move the rest to tomorrow?",
      "{count}! Your notebook's gonna be full of X's today!",
      "Today's score: {count} done! Clap clap clap!",
      "You got {count} done! Wangkko's tail is going wild!",
      "{count} cleared! Can't wait to see tomorrow's you!",
      "Wow, {count}! You really went for it today!",
      "{count} done! Mark the rest with > and rest up."
    ],
    wrapUpZero: [
      "Zero today is okay! Everyone needs a rest day.",
      "Tomorrow morning, let's start with the smallest one together. Promise!",
      "Even with zero, opening your notebook today counts!",
      "Today was a recharge day! Let's run together tomorrow.",
      "It's okay, it's okay! Mark the rest with > and do them tomorrow.",
      "Taking a day off doesn't change it — you're still the best!"
    ],
    night: [
      "Time to sleep! See you tomorrow~",
      "Good night! Wangkko's already asleep.",
      "Phone down, eyes closed! I'll be waiting with my glasses on tomorrow morning.",
      "You did plenty today. Sleep well!",
      "Lights off, blanket on! Great work today.",
      "Glasses off. Now it's really bedtime!",
      "I'll be waiting with an iced americano tomorrow morning!",
      "Sweet dreams! Go on a walk with Wangkko in your dreams.",
      "Too much screen keeps you up! Let's shut it off.",
      "Leave today's worries in the notebook and sleep!",
      "Night night! Let's do it together tomorrow too, promise!",
      "Zzz~ I'm closing my eyes now too!"
    ],
    praise: [
      "Nice! That's {count}!",
      "Whoa, you did it!",
      "Okay, on to the next one!",
      "One down! {left} to go!",
      "See? You do it, and it gets done!",
      "One more X! Feels great!",
      "{count} and counting! You're unstoppable!",
      "Amazing! You actually did it!",
      "Only {left} left! Almost there!",
      "High five! Smack!",
      "Wangkko barked instead of clapping!",
      "Knew it! I knew you could!",
      "{count} done, {left} to go! Keep this momentum!",
      "Draw that X in your notebook! So satisfying!",
      "Yes! Same vibe for the next one!",
      "That just now was so cool!",
      "Another one done! You're flying today!",
      "{left} left. Let's finish them together!"
    ],
    praiseAll: [
      "Everything cleared!! Today was incredible!",
      "Zero left on today's list! High five!",
      "List wiped clean!! Today's MVP is you!",
      "All clear! Let's take Wangkko on a celebration walk!",
      "All X's! Your notebook is sparkling!",
      "I can't believe you did it all! Melon bread celebration!"
    ],
    migrate: [
      "Moved it to tomorrow! Let's start with it first thing.",
      "It's okay to push it back. But it's number one tomorrow!",
      "Okay, tomorrow's us will handle it!",
      "Marked with >! I'll put it at the top of tomorrow's list.",
      "That's it for today! Moving it is part of the plan.",
      "Moved! But tomorrow, even just five minutes, okay?",
      "Moved into tomorrow! Wangkko will guard it.",
      "If it keeps getting moved, let's break it smaller!",
      "It's fine — you didn't drop it, you moved it!"
    ],
    schedule: [
      "I'll remind you on {date}! Marked on the calendar.",
      "I'll come talk to you first that day!",
      "{date}! Got it. I'll poke you that morning.",
      "Booked for {date}! Let's write it in your notebook too.",
      "Don't worry, even if you forget, I'll remember!",
      "Date's set, so relax for today!"
    ],
    focusStart: [
      "5-minute timer, go!",
      "Just five minutes! Let's go!",
      "Countdown started~ I'll cheer for you quietly!",
      "Start! Let's close the other windows for now.",
      "Five minutes, ready~ go!",
      "Timer's running! Just do the first line.",
      "Focus mode ON! Wangkko's lying down to wait too.",
      "Five minutes is longer than you think! You've got this!",
      "Go! When it's over, I'll clap the loudest!"
    ],
    focusDone: [
      "Five minutes done! Wanna go another round?",
      "See, you did five minutes! Keep going?",
      "Ding dong! Five minutes, success! Awesome!",
      "Five minutes up! If you're in the flow, keep riding it!",
      "You did it! Another round? Or a glass of water?",
      "Five minutes cleared! Starting isn't scary anymore, right?"
    ],
    focusStop: [
      "Even five minutes counts! That's totally different from zero.",
      "Starting is the most amazing part!",
      "It's fine to stop! What you did still counts.",
      "Okay, let's rest! Next time, start with three minutes?",
      "Just touching it means progress!",
      "Good job! Call me when you want to go again."
    ],
    focusKeep: [
      "Great! I won't bother you.",
      "Then I'll be right here cheering quietly!",
      "Ooh, you're keeping going! Awesome!",
      "Okay, my lips are sealed!",
      "Keep going before the flow breaks!",
      "Wangkko and I will stay quietly by your side!"
    ],
    snooze: [
      "Got it! I'll call you again in 20 minutes.",
      "Snooze is on. Let's do it together then!",
      "Okay! I'll be back in 20 minutes — no running away!",
      "Take a little break! But next time we do it together for sure.",
      "Set a 20-minute timer. Drink some water meanwhile!",
      "Alarm's set! Next reminder, we head out right away!"
    ],
    music: [
      "Ooh, I like this song!",
      "It goes better when you're grooving, right?",
      "How many times has this one looped? I love it too!",
      "Turn it up just a notch!",
      "Wangkko's keeping the beat with his tail!",
      "Humming along with you~",
      "Ooh, nice beat! Your fingers must be loving it!",
      "Headphones on! I'm listening with you.",
      "Let's finish one task before this song ends!",
      "This song makes me wanna go on a walk!",
      "With music on, work feels like a festival!",
      "Head bobbing~ I'm dancing right now!",
      "This playlist has great taste!",
      "Here comes the chorus! Sing along!",
      "Don't stop typing while you sing along!",
      "Chill songs are nice too~ Great for focus.",
      "At this tempo, you could finish two tasks!",
      "Just keep the volume easy on your ears!"
    ],
    musicTitle: [
      "{title}! Do you like this song?",
      "{title}… I'm adding it to my playlist too!",
      "{title} is on! This one's upbeat, right?",
      "{title}! I love the title already!",
      "Let's finish one task to {title}!",
      "Oh, {title}! You've got good taste!"
    ],
    poke: [
      "Hm? You called?",
      "What's up, what's up! Wanna look at your tasks together?",
      "You scared me! …Hehe, what's up?",
      "Wangkko reacted first!",
      "That tickles! Hehe.",
      "Did you call me? Need any help?",
      "You knocked my glasses crooked~ Troublemaker!",
      "You poked me, so now you do a task!",
      "Wangkko wants pets too!",
      "Yep yep, I'm here! Were you bored?",
      "Whoa! I almost spilled my iced americano!",
      "You just missed me, right? Me too!"
    ],
    batteryLow: [
      "Laptop battery's at {level}%! Plug in the charger!",
      "{level}%! Charge me before I shut off!",
      "{level}% battery left! Where'd you put the charger?",
      "{level}%! Save, then plug in!",
      "The laptop's hungry. It's at {level}%!",
      "{level}% warning! Wangkko's about to fetch the charger."
    ],
    batteryVeryLow: [
      "Battery {level}%! Save first, quick!",
      "{level}%… Where's the charger? Let's find it together!",
      "{level}%!! Ctrl+S right now!",
      "Real danger, {level}%! Charger, go!",
      "{level}%… Save your work before it dies!",
      "Battery {level}%! It's about to go dark for me!"
    ],
    batteryFull: [
      "100% charged! You can unplug now.",
      "Fully charged! We're set for the whole day!",
      "Battery full! Let's run as much as we want today!",
      "100% charged! Let the charger take a break.",
      "Full! My energy's maxed out too!",
      "Charging done! Unplug and roam free!"
    ],
    renderStart: [
      "Render's running! Let's stretch while we wait!",
      "The computer's working! We get a glass of water.",
      "Let's tidy up the notebook while it renders!",
      "Render's off! Wanna knock out a u task meanwhile?",
      "Render started! You can take Wangkko for a quick walk.",
      "Go, computer! We'll rest our eyes.",
      "Great job getting the render going! Starting is half!",
      "Let's make an iced americano while it renders!",
      "Now we wait! Wanna peek at the next task?"
    ],
    renderWait: [
      "Still rendering~ Just a little more!",
      "Those fans are working hard!",
      "Staring at the progress bar makes it feel slower. Let's do something else!",
      "Waiting is part of the work too!",
      "Just a bit more~ It's probably almost there!",
      "Don't open anything heavy while it renders!",
      "While we wait — anything to X off in the notebook?",
      "Wangkko's waiting in front of the screen with us!",
      "The computer's working hard! Let's cheer it on.",
      "Neck stretch while you wait for the render!",
      "I'll tell you the second it's done!",
      "Let's wait it out. It's gonna come out great!"
    ],
    renderDone: [
      "Render's done! Let's see it!",
      "All done! If it came out great, high five!",
      "Render complete! Nice work!",
      "Ta-da! Render complete!",
      "It's out! How is it, do you like it?",
      "Render finished! Don't forget to save the file!",
      "Worth the wait! It looks amazing!",
      "Done! Let's put an X in the notebook!",
      "Render's done! Wangkko's wagging his tail too!"
    ],
    strainCpu: [
      "The computer's hot! What are you running?",
      "The CPU is panting. Let's close the programs you're not using!",
      "The fans are screaming! Let's give it a breather.",
      "CPU's at full throttle! Wanna check background apps?",
      "Laptop's toasty! Put it on the desk, not your lap.",
      "The computer needs to breathe too! Close just one thing."
    ],
    strainRam: [
      "Memory's full! Let's close some tabs.",
      "That's way too many windows! Let's tidy up a few.",
      "How many tabs?! Let's close the ones you're not using.",
      "Memory's gasping! Bookmark them and close.",
      "Tidy your windows, tidy your mind!",
      "Close one program and everything'll speed up!"
    ],
    tie: [
      "Glasses on! Now we're really starting!",
      "First one done! Glasses on, engine on!",
      "Now the world's finally clear! Let's go!",
      "Glasses on, motivation doubled!",
      "One done — now it's real Suu mode!",
      "Glasses gleaming! I can see the next task clearly!",
      "Engine started! Full speed ahead!",
      "Pushing up my glasses… okay, focus!",
      "First X is in! Glasses officially earned!"
    ],
    switchIn: [
      "Hi! It's my turn now. Let's do this together!",
      "Suu, reporting for duty! Show me your task list!",
      "Baton pass! Now let's have fun with Suu!",
      "Ta-da! I'm here. Brought Wangkko too!",
      "My turn! Let's start with the smallest one together.",
      "Suu's here! How many tasks are in the notebook today?"
    ],
    btLow: [
      "{name} battery's at {level}%! Let's charge it.",
      "{name} looks like it's about to die. {level}%!",
      "{name} has {level}% left! Plug it in.",
      "{name} at {level}%… It'd be sad if it cut out!",
      "Oops, {name} is at {level}%! Charge it on your break.",
      "{name} is running low. {level}%! Feed it!"
    ]
  };
  const PROFILE = {
    hanja: '水 · water',
    quote: "Let's just do one! After one, two comes fast.",
    facts: [
      ['Personality', "A sunny, outgoing cheerleader. He knows starting is the hardest part, so he takes that first step with you. Praises big, and often."],
      ['Likes', 'Iced americanos, melon bread, walks, watching X marks pile up in the notebook'],
      ['Dislikes', 'Struggling alone, skipping meals'],
      ['Companion', 'Wangkko — a golden retriever puppy. First to come running at the smell of snacks'],
      ['Habits', 'Dazed without his glasses in the morning; puts them on and gets going after the first task. When music plays, he puts on headphones and grooves along']
    ]
  };
  (root.LineBanks = root.LineBanks || {})['suu:en'] = LINES;
  (root.ProfileBanks = root.ProfileBanks || {})['suu:en'] = PROFILE;
  if (typeof module !== 'undefined' && module.exports) module.exports = { LINES, PROFILE };
})(typeof window !== 'undefined' ? window : globalThis);
